sudo: true
os: linux
language: go
go: [1.9.2]
go_import_path: github.com/mysterium/node

env:
  global:
    - CACHE_ROOT_DIR=$HOME/cache
    - BUILD_TOOLS_PATH=$CACHE_ROOT_DIR/build_tools
    - GLIDE_HOME=$HOME/glide-home
    - BUILD_COMMIT=$TRAVIS_COMMIT
    - BUILD_BRANCH=$TRAVIS_BRANCH
    - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    - BUILD_VERSION_MAJOR=0

cache:
  directories:
    - "$CACHE_ROOT_DIR"

install:
  - source bin/travis_scripts/setup_tools_dir.sh $BUILD_TOOLS_PATH
  - source bin/travis_scripts/ensure_glide.sh $BUILD_TOOLS_PATH "v0.13.1"
  - bin/travis_scripts/ensure_xgo.sh
  - glide "-home" $GLIDE_HOME install

script:
  - export BUILD_VERSION=${TRAVIS_TAG:-"$BUILD_VERSION_MAJOR-dev.$TRAVIS_BUILD_NUMBER"}
  - bin/check_vet
  # This check requires development dependency
  - bin/builder_run bin/check_lint
  - bin/check_fmt
  - bin/check_license
  - bin/test
  # Run e2e tests (on Pull Requests only)
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      bin/travis_scripts/check_docker.sh;
      bin/travis_scripts/check_docker_compose.sh;
      bin/test_e2e;
      bin/package_all $BUILD_VERSION;
    fi
  #ugly hack - will be removed when stages will be introduced
  #we need to package everything on master and tags too - not only on PR's
  - if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ]; then
      bin/package_all $BUILD_VERSION;
    fi

deploy:
  # Development bleeding-edge release (on master commits only)
  - provider: pages
    local-dir: build/package
    skip-cleanup: true
    github-token: "$GIT_RELEASES_API_KEY"
    keep-history: false
    target-branch: mysterium-node
    repo: MysteriumNetwork/build-artifacts
    on:
      tags: false
      branch: master
  - provider: script
    script: bin/release_docker dev
    on:
      tags: false
      branch: master
  # Official release (on tags only)
  - provider: releases
    file_glob: true
    file: build/package/*
    skip_cleanup: true
    api_key: "$GIT_RELEASES_API_KEY"
    on:
      tags: true
  - provider: script
    script: bin/release_docker $TRAVIS_TAG latest
    on:
      tags: true
notifications:
  slack:
    rooms:
      - secure: >
          uzg7QbKd09rm6q/7iXk1HFfXo61vqFbENueRM/a6Jg+o2/YZEQXtKLO+gLg2gY/4ok9P4goUF8PuAA1/YLnhzJAr0ks35z69kns36E2eJkU2kB72D8
          K44Mi5fhPFrcbbkPPqFtMoeXUkEjNvB6LT3w0xpWOUBS68N/HJrpi2Y3kn1tp96tcsneLyBick3JrlJc3aptHq/bNFLaWFS9orzcp9wWDjxNeWaVze
          GM0Y1GCFQymff9UOf2r6Vy/MjESo9QjHH+gJbEzH13d6YcBi2ktZF3c6ZDqsjOOQZKQzwrgYk6sVLQsikDtA0vPgXVVyTVgcYmdTrNF6K/31Dt/e3K
          gJXvpwn6tsW6o2DJJpq4MXFOm2z+S20KNbhSj5BLzYmVOKnJhyDAFFYWLDfF0ZJs3D0Pezjtu8HsMvkX3REYXUaBEZuRR4GRV4iqCdyHWKR+WGtX7Y
          FfsaolqNiWAqHaACH5jL2oZ4DcwF3x0LfEpESJYJrmmUsCl0/siBe9e5zL3mpwdJ7vG2rH8XUsEJvHf5A8YSYOSLE06lPpioNjskKoGYT0/c8VNAty
          OvkdfTsWhz6oCOAZyJsQPuW1vEkjdK/mkrj38g0K4RnMQ05aVbLlHkH+1OUzzPl/NVydoDYdTlkCYTDSL3vrD/Uh5uu57FDssUkz/joiuzixNkePo=
    on_success: change
    on_failure: always
