version: '3'
services:

  broker:
    image: nats
    expose:
      - 4222
      - 8222

  #infrastructure - centralized api and db
  db:
    image: percona:5.7
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myst_api
      MYSQL_USER: myst_api
      MYSQL_PASSWORD: myst_api

  discovery:
    image: mysteriumnetwork/mysterium-api:0.1.12
    expose:
    - 80
    environment:
      APP_PORT: 80
      DB_HOST: db
      DB_NAME: myst_api
      DB_USER: myst_api
      DB_PASSWORD: myst_api
    depends_on:
    - db

  local-node:
    image: docker-geth:1.8.12
    expose:
      - 8545
    volumes:
      - geth-runtime:/ethereum/geth-runtime
      - ./devnet_genesis.json:/ethereum/genesis.json
      - ./node:/ethereum/keystore
      - ./node_acc_password.txt:/ethereum/node_acc_password.txt
    command: >
      --syncmode 'full'
      --port 30311
      --rpc
      --rpcaddr 'localhost'
      --rpcport 8545
      --rpcapi 'personal,db,eth,net,web3,txpool,miner'
      --networkid 69
      --gasprice '1'
      --unlock '0xd9786b6ee6caf5cd0ef88301fc40de83bfac5594'
      --password node_acc_password.txt
      --mine

volumes:
  geth-runtime: