version: '3'
services:

  node:
    build:
      context: ../..
      dockerfile: bin/server_docker/alpine/Dockerfile
    depends_on:
      - broker
      - discovery
      - ipify
    cap_add:
      - NET_ADMIN
    expose:
      - 1194
    command: >
      --ipify-url=http://ipify:3000
      --broker-address=broker
      --discovery-address=http://discovery/v1
      --location.country=e2e-land
      --openvpn.port=3000
      --agreed-terms-and-conditions

  client:
    build:
      context: ../..
      dockerfile: bin/client_docker/alpine/Dockerfile
    depends_on:
      - broker
      - node
      - discovery
      - ipify
    cap_add:
      - NET_ADMIN
    expose:
      - 4050
    command: >
      --ipify-url=http://ipify:3000
      --discovery-address=http://discovery/v1
      --localnet
      --ether.client.rpc=http://local-node:8545

  #'external' IP detection
  ipify:
    image: owlab/ipify
    expose:
    - 3000
